sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  code_climate:
    repo_token: 8a17454c3cc8f51a8013ca48380c95b5c6337ea9fa9941377d63031f86ba77b2
